### ISSUE TITLE
notification media click not working

### ISSUE THREAD

**Issue by muslimdeveloper** [prokash-sarkar/PexoPlayer#1]
can you give example how to use notification media when clicked audio is play/pause/next/prev

**Comment by prokash-sarkar** [comment]
Hi, Thank you for trying PexoPlayer in its initial stage. I'm currently working the sample app which will include the necessary code samples.

Notification will show automatically once you set the playlist correctly. The track title & image will also change in notification based on the song currently playing in PexoPlayer. 

Regarding the Play/Pause/Next/Prev button, the notification will handle it for you. It's **embedded inside the library**. Just set the track and enjoy.

If there's a track change in notification with "**Next/Previous**" button, you will get an event in
```onPlayerMetadataChanged(PexoMediaMetadata metadata){}```

If there's a playback state change in notification with "**Play/Pause**" button, you will get an event in ```onPlayerPlaybackStateChanged(PlaybackStateCompat state){}```

Just set an activity for the pending intent, so that a click on notification will get back to your activity

```pexoPlayerManager.setPendingIntentClass(MainActivity.class);```

Also, Please check the updated documentation.

**Comment by muslimdeveloper** [comment]
thanks it's work, can i request onStop() audio? it's will be delete notification play and playlist

**Comment by prokash-sarkar** [comment]
Please try `pexoPlayerManager.onStop()` followed by version `v1.0.0-alpha-2-java`.  Once the media is stopped you need to dismiss the notification manually. 

Currently, there's no method for clearing the playlist. You can set an empty playlist or just use a new playlist to replace the old one.
